---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	supervisor(supervisor)
	routine_agent(routine_agent)
	device_agent(device_agent)
	robot_cleaner_agent(robot_cleaner_agent)
	__end__([<p>__end__</p>]):::last
	__start__ --> supervisor;
	device_agent --> supervisor;
	robot_cleaner_agent --> supervisor;
	routine_agent --> supervisor;
	supervisor -.-> routine_agent;
	supervisor -.-> device_agent;
	supervisor -.-> robot_cleaner_agent;
	supervisor -.-> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
